"""Load the governed business context — the semantic-memory tier.

This is what stops the engine inventing its own definition of "revenue". Both YAML
contracts are loaded on every run and exposed as typed objects. Nothing here is
generated by an LLM; it is human-authored governance.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache

import yaml

from .config import PERSONAS, SEMANTIC_CONTRACT


@dataclass
class KPISpec:
    name: str
    label: str
    definition: str
    calculation: str
    source: str
    grain_out: str
    unit: str
    drivers: list[str]
    materiality: dict
    lineage: list[str]
    access: str                       # entitlement tag: finance_restricted | operational_open
    caveats: str = ""


@dataclass
class SemanticContract:
    version: str
    calendar: dict
    sources: dict
    kpis: dict                        # name -> KPISpec
    causal_priors: list[dict]

    def kpi(self, name: str) -> KPISpec:
        if name not in self.kpis:
            raise KeyError(f"KPI '{name}' is not governed by the semantic contract. "
                           f"Known: {list(self.kpis)}")
        return self.kpis[name]

    def source_freshness(self, kpi_name: str) -> dict:
        """Return the source's refresh cadence + freshness SLA for evidence display (#8)."""
        src = self.kpi(kpi_name).source
        s = self.sources[src]
        return {"source": src, "system": s["system"], "grain": s["grain"],
                "refresh": s["refresh"], "freshness_sla_hours": s["freshness_sla_hours"],
                "governance": s["governance"]}


@dataclass
class Persona:
    key: str
    label: str
    goal: str
    entitlements: list[str]           # access tiers this persona holds
    row_scope: dict                   # e.g. {"geo_region": "SP,PR,SC,RS"} or {"geo_region": "*"}
    narrative: dict
    action_style: str
    channel: str

    def can_see(self, access_tag: str) -> bool:
        """Column/domain-level check: may this persona read a KPI with this access tag?"""
        return access_tag in self.entitlements

    def region_filter(self) -> list[str] | None:
        """Row-level scope -> list of allowed regions, or None for all."""
        val = self.row_scope.get("geo_region", "*")
        if val == "*":
            return None
        return [v.strip() for v in val.split(",")]


@lru_cache(maxsize=1)
def load_semantic_contract() -> SemanticContract:
    raw = yaml.safe_load(SEMANTIC_CONTRACT.read_text())
    kpis = {name: KPISpec(name=name, **spec) for name, spec in raw["kpis"].items()}
    return SemanticContract(
        version=raw["version"], calendar=raw["calendar"], sources=raw["sources"],
        kpis=kpis, causal_priors=raw["causal_priors"],
    )


@lru_cache(maxsize=1)
def load_personas() -> dict[str, Persona]:
    raw = yaml.safe_load(PERSONAS.read_text())
    out = {}
    for key, p in raw["personas"].items():
        out[key] = Persona(key=key, label=p["label"], goal=p["goal"],
                           entitlements=p["entitlements"], row_scope=p["row_scope"],
                           narrative=p["narrative"], action_style=p["action_style"],
                           channel=p["channel"])
    return out


def entitlement_scenario() -> dict:
    return yaml.safe_load(PERSONAS.read_text())["entitlement_scenario"]
